fragment ProjectFragment on Project {
    id
    name,
    domain,
    models,

    email,
    emailWelcomeTitle,
    emailWelcomeMessage,
    emailForgottenPasswordMessage,
    emailForgottenPasswordTitle
    _error
}