fragment ProjectFragment on Project {
    id
    name,
    domain,
    models,

    email,
    emailWelcomeTitle,
    emailWelcomeMessage,
    emailForgottenPasswordMessage,
    emailForgottenPasswordTitle,

    loginFacebookId,
    loginFacebookSecret,
    loginGmailId,
    loginGmailSecret,
    loginGithubId,
    loginGithubSecret,

    _error
}