fragment ProjectFragment on ProjectModel {
  id
  name
  domain
  models

  email
  emailWelcomeTitle
  emailWelcomeMessage
  emailForgottenPasswordMessage
  emailForgottenPasswordTitle

  loginFacebookId
  loginFacebookSecret
  loginFacebookCallbackURL

  loginGithubId
  loginGithubSecret
  loginGithubCallbackURL

  loginGmailId
  loginGmailSecret
  loginGmailCallbackURL

  _error
}
